export const sideNavCnname = [
    {
        "Dashboard": "控制台",
        "Product": "商品",
        "ProductAdmin": "商品管理",
        "ProductCreate": "添加商品",
        "ProductList": "商品列表",
        "ProductCategory": "商品分类",
        "GroupAdmin": "分组管理",
        "TypeAdmin": "类型管理",
        "BrandAdmin": "品牌管理",
        "TagAdmin": "标签管理",
        "Order": "订单",
        "DealAdmin": "订单栏目",
        "OrderList": "订单列表",
        
        "Customer": "客户",
        "MemberCenter": "会员中心",
        "MemberList": "会员列表",
        "MemberGroup": "会员分组",
        "MemberCard": "会员卡",
        "CommunityUserlist": "社区会员",
        "BranchAgent": "分公司列表",
        "BranchInfo": "分公司",
        "BranchDistributor": "分销商列表",
        "BranchReport": "分公司",
        "CustomerEchart": "会员报表",
        "UnionMerchant" : "联促商家",
        "Merchant" : "商家列表",
        "Distributor": "分销商",
        "DistributorList": "分销商列表",
        "SalesRankings": "销售排行",
        "Agent": "合伙人",
        "AgentCreate": "添加合伙人",
        "AgentList": "合伙人列表",
        
        "Setting": "设置",
        "ShopSetting": "商城设置",
        "BaseSettings": "基础设置",
        "ShopNav": "商城导航",
        "ShopStyle": "商城风格",
        "ShopPage": "自定义页面",
        "ShopNotice": "消息公告",
        "ShopService": "在线客服",
        "ReceivableAccount": "收款账号",
        "AccountSetting": "账号设置",
        "WithdrawSetting": "提现设置",
        "OSSystemSettings": "系统设置",
        "RolesSettings": "角色管理",
        "AuditLogsSettings": "审计日志",
        "MaintenanceSettings": "维护",
        "OrdersEchart": "订单报表",
        "OrdersQtyEchart": "订单总数",
        "OrdersAmountEchart": "订单金额",
        "OrdersRechargeAmount": "充值总额",
        "UserRegionReport": "全国会员分布",
        "UserPermissionSettings": "用户权限",
        "OilBeanLogStatistics": "油豆分析",
        "OilCardList": "油卡列表",
        "MessageCenter": "消息中心",
        "MessagePush": "消息推送",
        "BusinessCollegeArticle": "商学院文章",
        "CommissionLogStatistics": "佣金分析",
        "RankEchart": "排行榜",
        "SaleRankanAlysis": "销售排行榜",
        "BranchSaleReport": "分公司销售",
        "SaleRankReport": "销售排行榜",
        "MemberIncomeRank": "会员收益排行榜",
        "FeedbackSystem": "反馈中心",
        "UserFeedback": "用户反馈",
        "YouXiaoMi": "油小蜜",
        "YouXiaoMiOrders": "订单列表",
        "YouXiaoMiPrivilege": "特权服务",
        "YouXiaoMiUser": "用户列表",
        "MallOrderList": "订单列表",
        "DealMallAdmin": "商城订单",
        "FreightTemplateAdmin": "运费模板管理",
        "PurifierWater": "净水器订单",
        "PurifierWaterReport": "净水器报表",
        "SystemDocumentation": "系统文件"
    }
];